on: 
  pull_request: 
    types:
      - closed

name: example

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master    

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        namespace: pr-${{ github.event.number }}
    
    - name: "Destroy the pipeline"
      uses: okteto/destroy-pipeline@master
      with:
        name: pr-${{ github.event.number }}
